name: dialyzer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  dialyzer:
    runs-on: ubuntu-latest

    env:
      CACHE_VERSION: v1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        id: beam
        with:
          elixir-version: '1.10'
          otp-version: '22.0'

      - name: Restore dep and build cache
        uses: actions/cache@v2
        id: dep_build_cache
        with:
          key: |
            ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
          path: |
            deps
            _build

      - name: Restore dep and build cache
        uses: actions/cache@v2
        id: plt_cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts

      - name: Install dependencies
        run: mix deps.get

      - name: Generate PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer
